global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "app"
    static_configs:
      - targets: ['127.0.0.1:8080']